name: Build project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/qtroot/'
        install-deps: 'true'
        cached: 'false'
        setup-python: 'true'
        tools: ''
        set-env: 'false'
        tools-only: 'false'
        aqtversion: '==2.0.0'
        py7zrversion: '==0.16.1'
        extra: '--external 7z'
      
    
    - name: build
      env:
        QT5_BIN: "${{ github.workspace }}/qtroot/Qt/5.15.2/msvc2019_64/bin"
      run: |
      
        Write-Host "QT5_BIN = $Env:QT5_BIN"

        mkdir build
        cd build
        & "${{ env.QT5_BIN}}/qmake.exe" "..\src\FileCopy.pro"
        nmake

    - uses: actions/upload-artifact@v3
      with:
        name: FileCopy
        path: build/release/FileCopy.exe